"""Registry of every upstream source the atlas uses.

Each entry is cited on the site (methodology + data pages), so keep titles,
publishers and licences accurate. `kind` controls how fetch.py stores it.
"""

OPENDOSM = "Department of Statistics Malaysia (DOSM), via OpenDOSM"
CC_BY = "CC BY 4.0"

SOURCES = [
    # --- District-level open data (parquet) ---
    dict(id="gdp_district", kind="parquet",
         url="https://storage.dosm.gov.my/gdp/gdp_district_real_supply.parquet",
         title="Annual Real GDP by District & Economic Sector",
         catalogue="https://open.dosm.gov.my/data-catalogue/gdp_district_real_supply",
         publisher=OPENDOSM, licence=CC_BY, years="2015–2020",
         note="RM million, constant 2015 prices. Place of production."),
    dict(id="gdp_state", kind="parquet",
         url="https://storage.dosm.gov.my/gdp/gdp_state_real_supply.parquet",
         title="Annual Real GDP by State & Economic Sector",
         catalogue="https://open.dosm.gov.my/data-catalogue/gdp_state_real_supply",
         publisher=OPENDOSM, licence=CC_BY, years="2015–latest"),
    dict(id="lfs_district", kind="parquet",
         url="https://storage.dosm.gov.my/labour/lfs_district.parquet",
         title="Annual Principal Labour Force Statistics by District",
         catalogue="https://open.dosm.gov.my/data-catalogue/lfs_district",
         publisher=OPENDOSM, licence=CC_BY, years="2018–2024",
         note="Place of residence. DOSM advises caution: high relative standard error at district level."),
    dict(id="population_district", kind="parquet",
         url="https://storage.dosm.gov.my/population/population_district.parquet",
         title="Population Table: Administrative Districts",
         catalogue="https://open.dosm.gov.my/data-catalogue/population_district",
         publisher=OPENDOSM, licence=CC_BY, years="2020–2025", note="Thousands."),
    dict(id="population_state", kind="parquet",
         url="https://storage.dosm.gov.my/population/population_state.parquet",
         title="Population Table: States",
         catalogue="https://open.dosm.gov.my/data-catalogue/population_state",
         publisher=OPENDOSM, licence=CC_BY, years="1970–latest", note="Thousands."),
    dict(id="population_malaysia", kind="parquet",
         url="https://storage.dosm.gov.my/population/population_malaysia.parquet",
         title="Population Table: Malaysia",
         catalogue="https://open.dosm.gov.my/data-catalogue/population_malaysia",
         publisher=OPENDOSM, licence=CC_BY, years="1970–latest", note="Thousands."),
    dict(id="births_district", kind="parquet",
         url="https://storage.dosm.gov.my/demography/birth_district_sex.parquet",
         title="Annual Live Births by District & Sex",
         catalogue="https://open.dosm.gov.my/data-catalogue/births_district_sex",
         publisher=OPENDOSM, licence=CC_BY, years="varies"),
    dict(id="deaths_district", kind="parquet",
         url="https://storage.dosm.gov.my/demography/death_district_sex.parquet",
         title="Annual Deaths by District & Sex",
         catalogue="https://open.dosm.gov.my/data-catalogue/deaths_district_sex",
         publisher=OPENDOSM, licence=CC_BY, years="varies"),
    dict(id="hh_income_district", kind="parquet",
         url="https://storage.dosm.gov.my/hies/hh_income_district.parquet",
         title="Household Income by Administrative District",
         catalogue="https://open.dosm.gov.my/data-catalogue/hh_income_district",
         publisher=OPENDOSM, licence=CC_BY, years="2019, 2022, 2024", note="RM per month, nominal."),
    dict(id="hh_poverty_district", kind="parquet",
         url="https://storage.dosm.gov.my/hies/hh_poverty_district.parquet",
         title="Poverty by Administrative District",
         catalogue="https://open.dosm.gov.my/data-catalogue/hh_poverty_district",
         publisher=OPENDOSM, licence=CC_BY, years="2019, 2022, 2024"),
    dict(id="hh_inequality_district", kind="parquet",
         url="https://storage.dosm.gov.my/hies/hh_inequality_district.parquet",
         title="Income Inequality by District",
         catalogue="https://open.dosm.gov.my/data-catalogue/hh_inequality_district",
         publisher=OPENDOSM, licence=CC_BY, years="2019, 2022, 2024"),
    dict(id="hies_district", kind="parquet",
         url="https://storage.dosm.gov.my/hies/hies_district.parquet",
         title="Household Income and Expenditure: Administrative Districts",
         catalogue="https://open.dosm.gov.my/data-catalogue/hies_district",
         publisher=OPENDOSM, licence=CC_BY, years="2022, 2024"),
    dict(id="hh_income_state", kind="parquet",
         url="https://storage.dosm.gov.my/hies/hh_income_state.parquet",
         title="Household Income by State",
         catalogue="https://open.dosm.gov.my/data-catalogue/hh_income_state",
         publisher=OPENDOSM, licence=CC_BY, years="1970–2024"),
    dict(id="hh_poverty_state", kind="parquet",
         url="https://storage.dosm.gov.my/hies/hh_poverty_state.parquet",
         title="Poverty by State",
         catalogue="https://open.dosm.gov.my/data-catalogue/hh_poverty_state",
         publisher=OPENDOSM, licence=CC_BY, years="1970–2024",
         note="Poverty line methodology revised in 2019; earlier years are not comparable."),
    dict(id="hh_inequality_state", kind="parquet",
         url="https://storage.dosm.gov.my/hies/hh_inequality_state.parquet",
         title="Income Inequality by State",
         catalogue="https://open.dosm.gov.my/data-catalogue/hh_inequality_state",
         publisher=OPENDOSM, licence=CC_BY, years="1970–2024"),
    dict(id="hies_malaysia", kind="parquet",
         url="https://storage.dosm.gov.my/hies/hh_income.parquet",
         title="Household Income: Malaysia",
         catalogue="https://open.dosm.gov.my/data-catalogue/hh_income",
         publisher=OPENDOSM, licence=CC_BY, years="1970–2024"),
    dict(id="poverty_malaysia", kind="parquet",
         url="https://storage.dosm.gov.my/hies/hh_poverty.parquet",
         title="Poverty: Malaysia",
         catalogue="https://open.dosm.gov.my/data-catalogue/hh_poverty",
         publisher=OPENDOSM, licence=CC_BY, years="1970–2024"),
    dict(id="crops_district_area", kind="parquet",
         url="https://storage.data.gov.my/agriculture/crops_district_area.parquet",
         title="Crop Area by District",
         catalogue="https://data.gov.my/data-catalogue/crops_district_area",
         publisher="Department of Agriculture, via data.gov.my", licence=CC_BY, years="2017",
         note="Excludes paddy, oil palm and rubber."),
    # --- State-level tables published only as PDF ---
    dict(id="lfs_annual_2024", kind="pdf",
         url="https://storage.dosm.gov.my/labour/lfs_annual_2024.pdf",
         title="Labour Force Survey Report, Malaysia, 2024 (Tables B4.5, B4.8)",
         catalogue="https://www.dosm.gov.my",
         publisher="Department of Statistics Malaysia (DOSM)", licence="Source: DOSM (attribution)",
         years="2024", note="Employed persons by state × industry and state × occupation."),
    dict(id="lfs_annual_2023", kind="pdf",
         url="https://storage.dosm.gov.my/labour/lfs_annual_2023.pdf",
         title="Labour Force Survey Report, Malaysia, 2023 (Tables B4.5, B4.8)",
         catalogue="https://www.dosm.gov.my",
         publisher="Department of Statistics Malaysia (DOSM)", licence="Source: DOSM (attribution)",
         years="2023"),
    # --- Boundaries ---
    dict(id="boundaries", kind="kawasanku",
         url="https://open.dosm.gov.my/dashboard/kawasanku/Kedah/district/{district}",
         title="District boundaries (Kawasanku dashboard)",
         catalogue="https://open.dosm.gov.my/dashboard/kawasanku/Kedah",
         publisher=OPENDOSM, licence=CC_BY, years="2020 boundaries"),
    dict(id="context_boundaries", kind="kawasanku_context",
         url="https://open.dosm.gov.my/dashboard/kawasanku/{state}/district/{district}",
         title="Neighbouring district boundaries: Penang and Perlis (Kawasanku dashboard)",
         catalogue="https://open.dosm.gov.my/dashboard/kawasanku",
         publisher=OPENDOSM, licence=CC_BY, years="2020 boundaries",
         note="Drawn as grey context around the Kedah map."),
]

KEDAH_DISTRICTS = [
    "Baling", "Bandar Baharu", "Kota Setar", "Kuala Muda", "Kubang Pasu", "Kulim",
    "Langkawi", "Padang Terap", "Pendang", "Pokok Sena", "Sik", "Yan",
]


def slug(name: str) -> str:
    return name.lower().replace(" ", "-")

# Neighbours drawn as context on the map (state -> Kawasanku district names).
CONTEXT_DISTRICTS = {
    "Pulau Pinang": ["Barat Daya", "Timur Laut", "Seberang Perai Utara", "Seberang Perai Tengah", "Seberang Perai Selatan"],
    "Perlis": ["Perlis"],
}
